"""Generate the Career/provider template without loading user configuration."""
from __future__ import annotations

import argparse
import difflib
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Compatible names consumed by Career, Settings and the shared provider adapters.
CAREER_VARIABLES = {
    "WAKU_API_KEY": "Optional global credential override.",
    "WAKU_BASE_URL": "Optional global endpoint override.",
    "WAKU_MODEL": "Optional main model override.",
    "WAKU_SMALL_MODEL": "Compatible small-model override used by provider configuration.",
    "WAKU_HOME": "Runtime home; default ~/.waku, with legacy local-home discovery.",
    "WAKU_MAX_ITERATIONS": "Shared loop bound; default 10. Career stages cap this at 10.",
    "WAKU_MAX_TOKENS": "Output token bound; default 8192.",
    "WAKU_LLM_TIMEOUT": "Per-call timeout in seconds; default 120.",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "Optional tracing exporter; JSONL traces always persist.",
    "WAKU_DASHBOARD_HOST": "Career HTTP bind address; default 127.0.0.1.",
    "WAKU_DASHBOARD_PORT": "Career HTTP port; default 7777. Overrides PORT.",
    "PORT": "Compatible fallback HTTP port when WAKU_DASHBOARD_PORT is absent.",
}


def render_env_example(providers: dict | None = None) -> str:
    """Render registry credentials and retained configuration, without secrets."""
    if providers is None:
        providers = tomllib.loads((ROOT / "waku/providers.toml").read_text(encoding="utf-8"))
    lines = [
        "# Career Agent configuration. Generated by scripts/generate_env_example.py --write.",
        "# Configure a provider through Settings or copy this file to .env.",
        "# Process environment wins over working-directory .env, then runtime-home .env.",
        "# Commented assignments are optional; fill only the values you need.",
        "", "WAKU_PROVIDER=anthropic", "", "# Provider credentials and scoped overrides",
    ]
    for name, provider in providers.items():
        # Preserve the public template boundary for opt-in hidden provider rows.
        if provider.get("hidden_unless_env"):
            continue
        lines += ["", f"# {name}"]
        for field in ("key_env", "base_url_env", "model_env", "small_model_env"):
            variable = provider.get(field)
            if variable:
                lines.append(f"# {variable}=")
    lines += ["", "# Career and shared provider/runtime configuration"]
    for variable, description in CAREER_VARIABLES.items():
        lines += ["", f"# {description}", f"# {variable}="]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--path", type=Path, default=ROOT / ".env.example")
    args = parser.parse_args(argv)
    expected = render_env_example()
    if args.check:
        current = args.path.read_text(encoding="utf-8")
        if current == expected:
            return 0
        print("Career/provider environment example is out of date:")
        print("".join(difflib.unified_diff(current.splitlines(True), expected.splitlines(True),
                                         fromfile=str(args.path), tofile="generated")))
        return 1
    args.path.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
